### ISSUE TITLE
Broadcasting?

### ISSUE THREAD

**Issue by ghost** [migeyel/ecnet#2]
I would like to broadcast a message, while still making computers know its me.

It could work 2 ways, either computers connect to an address for receiving, and receive messages if the computer uses `.broadcast`.

OR, the same as above, but with channels, either way, it would be nice.

**Comment by migeyel** [comment]
The problem is that broadcasting would require either:

Using a signature scheme, but signatures are orders of magnitude slower than the symmetric primitives used in tunnels and too slow to be practical in my opinion.

OR, sending one message in a tunnel for every receiver, but this scales very poorly with many receivers since it's O(n) work for the sender.

Maybe another way of doing it would be to find a very cheap signature scheme to use, though this would involve implementing new primitives and making braking changes to the protocol.
