### ISSUE TITLE
Setting address of PC manually

### ISSUE THREAD

**Issue by BitTim** [migeyel/ecnet#3]
Hi,
I wanted to know if it is possible to assign an address of a PC manually. In my case it would be nice to set the address of a DNS Server to not have to re-enter it into all my client scripts that I use in multiple worlds.

Thank you for your reply in advance

**Comment by migeyel** [comment]
This is impossible by design, otherwise an attacker could manually set their address to one of your computers and forge their access into your network.

If you really want this you can copy the `/.ecnet-secretseed` file from your DNS server into your your other worlds. However it may be unsafe to do so since ecnet assumes that only one computer owns any specific address. You'll need to ensure that all computers operate on networks that are inaccessible from each other, which only really true if you're playing alone in single player.
